// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC {
    public static Asana.Posture.Web.Ui2.Controllers.AccountController Account = new Asana.Posture.Web.Ui2.Controllers.T4MVC_AccountController();
    public static Asana.Posture.Web.Ui2.Controllers.HomeController Home = new Asana.Posture.Web.Ui2.Controllers.T4MVC_HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC {
}

   
namespace System.Web.Mvc {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class T4Extensions {
        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result) {
            return htmlHelper.ActionLink(linkText, result, null, null, null, null);
        }

        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result, object htmlAttributes, string protocol = null, string hostName = null, string fragment = null) {
            return htmlHelper.RouteLink(linkText, null, protocol ?? result.GetT4MVCResult().Protocol, hostName, fragment, result.GetRouteValueDictionary(), HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, ActionResult result, IDictionary<string, object> htmlAttributes, string protocol = null, string hostName = null, string fragment = null) {
            return htmlHelper.RouteLink(linkText, null, protocol ?? result.GetT4MVCResult().Protocol, hostName, fragment, result.GetRouteValueDictionary(), htmlAttributes);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result) {
            return htmlHelper.BeginForm(result, FormMethod.Post);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod) {
            return htmlHelper.BeginForm(result, formMethod, null);
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod, object htmlAttributes) {
            return BeginForm(htmlHelper, result, formMethod, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcForm BeginForm(this HtmlHelper htmlHelper, ActionResult result, FormMethod formMethod, IDictionary<string, object> htmlAttributes) {
            var callInfo = result.GetT4MVCResult();
            return htmlHelper.BeginForm(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary, formMethod, htmlAttributes);
        }

        public static void RenderAction(this HtmlHelper htmlHelper, ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            htmlHelper.RenderAction(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary);
        }

        public static MvcHtmlString Action(this HtmlHelper htmlHelper, ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return htmlHelper.Action(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary);
        }

        public static string Action(this UrlHelper urlHelper, ActionResult result) {
            return urlHelper.Action(result, null, null);
        }

        public static string Action(this UrlHelper urlHelper, ActionResult result, string protocol = null, string hostName = null) {
            return urlHelper.RouteUrl(null, result.GetRouteValueDictionary(), protocol ?? result.GetT4MVCResult().Protocol, hostName);
        }

        public static string ActionAbsolute(this UrlHelper urlHelper, ActionResult result) {
            return string.Format("{0}{1}",urlHelper.RequestContext.HttpContext.Request.Url.GetLeftPart(UriPartial.Authority),
                urlHelper.RouteUrl(result.GetRouteValueDictionary()));
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions);
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions, object htmlAttributes) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcHtmlString ActionLink(this AjaxHelper ajaxHelper, string linkText, ActionResult result, AjaxOptions ajaxOptions, IDictionary<string, object> htmlAttributes) {
            return ajaxHelper.RouteLink(linkText, result.GetRouteValueDictionary(), ajaxOptions, htmlAttributes);
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions) {
            return ajaxHelper.BeginForm(result, ajaxOptions, null);
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions, object htmlAttributes) {
            return BeginForm(ajaxHelper, result, ajaxOptions, HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes));
        }

        public static MvcForm BeginForm(this AjaxHelper ajaxHelper, ActionResult result, AjaxOptions ajaxOptions, IDictionary<string, object> htmlAttributes) {
            var callInfo = result.GetT4MVCResult();
            return ajaxHelper.BeginForm(callInfo.Action, callInfo.Controller, callInfo.RouteValueDictionary, ajaxOptions, htmlAttributes);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result) {
            return MapRoute(routes, name, url, result, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults) {
            return MapRoute(routes, name, url, result, defaults, null /*constraints*/, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, string[] namespaces) {
            return MapRoute(routes, name, url, result, null /*defaults*/, namespaces);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, object constraints) {
            return MapRoute(routes, name, url, result, defaults, constraints, null /*namespaces*/);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, string[] namespaces) {
            return MapRoute(routes, name, url, result, defaults, null /*constraints*/, namespaces);
        }

        public static Route MapRoute(this RouteCollection routes, string name, string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Create and add the route
            var route = CreateRoute(url, result, defaults, constraints, namespaces);
            routes.Add(name, route);
            return route;
        }

        // Note: can't name the AreaRegistrationContext methods 'MapRoute', as that conflicts with the existing methods
        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result) {
            return MapRouteArea(context, name, url, result, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults) {
            return MapRouteArea(context, name, url, result, defaults, null /*constraints*/, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, string[] namespaces) {
            return MapRouteArea(context, name, url, result, null /*defaults*/, namespaces);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, object constraints) {
            return MapRouteArea(context, name, url, result, defaults, constraints, null /*namespaces*/);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, string[] namespaces) {
            return MapRouteArea(context, name, url, result, defaults, null /*constraints*/, namespaces);
        }

        public static Route MapRouteArea(this AreaRegistrationContext context, string name, string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Create and add the route
            if ((namespaces == null) && (context.Namespaces != null)) {
                 namespaces = context.Namespaces.ToArray();
            }
            var route = CreateRoute(url, result, defaults, constraints, namespaces);
            context.Routes.Add(name, route);
            route.DataTokens["area"] = context.AreaName;
            bool useNamespaceFallback = (namespaces == null) || (namespaces.Length == 0);
            route.DataTokens["UseNamespaceFallback"] = useNamespaceFallback;
            return route;
        }

        private static Route CreateRoute(string url, ActionResult result, object defaults, object constraints, string[] namespaces) {
            // Start by adding the default values from the anonymous object (if any)
            var routeValues = new RouteValueDictionary(defaults);

            // Then add the Controller/Action names and the parameters from the call
            foreach (var pair in result.GetRouteValueDictionary()) {
                routeValues.Add(pair.Key, pair.Value);
            }

            var routeConstraints = new RouteValueDictionary(constraints);

            // Create and add the route
            var route = new Route(url, routeValues, routeConstraints, new MvcRouteHandler());

            route.DataTokens = new RouteValueDictionary();

            if (namespaces != null && namespaces.Length > 0) {
                route.DataTokens["Namespaces"] = namespaces;
            }

            return route;
        }

        public static IT4MVCActionResult GetT4MVCResult(this ActionResult result) {
            var t4MVCResult = result as IT4MVCActionResult;
            if (t4MVCResult == null) {
                throw new InvalidOperationException("T4MVC was called incorrectly. You may need to force it to regenerate by right clicking on T4MVC.tt and choosing Run Custom Tool");
            }
            return t4MVCResult;
        }

        public static RouteValueDictionary GetRouteValueDictionary(this ActionResult result) {
            return result.GetT4MVCResult().RouteValueDictionary;
        }

        public static ActionResult AddRouteValues(this ActionResult result, object routeValues) {
            return result.AddRouteValues(new RouteValueDictionary(routeValues));
        }

        public static ActionResult AddRouteValues(this ActionResult result, RouteValueDictionary routeValues) {
            RouteValueDictionary currentRouteValues = result.GetRouteValueDictionary();

            // Add all the extra values
            foreach (var pair in routeValues) {
                ModelUnbinderHelpers.AddRouteValues(currentRouteValues, pair.Key, pair.Value);
            }

            return result;
        }

        public static ActionResult AddRouteValues(this ActionResult result, System.Collections.Specialized.NameValueCollection nameValueCollection) {
            // Copy all the values from the NameValueCollection into the route dictionary
            nameValueCollection.CopyTo(result.GetRouteValueDictionary());
            return result;
        }

        public static ActionResult AddRouteValue(this ActionResult result, string name, object value) {
            RouteValueDictionary routeValues = result.GetRouteValueDictionary();
            ModelUnbinderHelpers.AddRouteValues(routeValues, name, value);
            return result;
        }
        
        public static void InitMVCT4Result(this IT4MVCActionResult result, string area, string controller, string action, string protocol = null) {
            result.Controller = controller;
            result.Action = action;
            result.Protocol = T4MVCHelpers.IsProduction() ? protocol : null;
            result.RouteValueDictionary = new RouteValueDictionary();
            result.RouteValueDictionary.Add("Area", area ?? "");
            result.RouteValueDictionary.Add("Controller", controller);
            result.RouteValueDictionary.Add("Action", action);
        }

        public static bool FileExists(string virtualPath) {
            if (!HostingEnvironment.IsHosted) return false;
            string filePath = HostingEnvironment.MapPath(virtualPath);
            return System.IO.File.Exists(filePath);
        }

        static DateTime CenturyBegin=new DateTime(2001,1,1);
        public static string TimestampString(string virtualPath) {
            if (!HostingEnvironment.IsHosted) return string.Empty;
            string filePath = HostingEnvironment.MapPath(virtualPath);
            return Convert.ToString((System.IO.File.GetLastWriteTimeUtc(filePath).Ticks-CenturyBegin.Ticks)/1000000000,16);            
        }
    }
}



namespace T4MVC {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}


  

   
[GeneratedCode("T4MVC", "2.0")]   
public interface IT4MVCActionResult {   
    string Action { get; set; }   
    string Controller { get; set; }   
    RouteValueDictionary RouteValueDictionary { get; set; } 
    string Protocol {get; set; }  
}   
  

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public class T4MVC_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult {
    public T4MVC_ActionResult(string area, string controller, string action, string protocol = null): base()  {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class libs {
            private const string URLPATH = "~/Scripts/libs";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
                          
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap {
                private const string URLPATH = "~/Scripts/libs/bootstrap";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string alert_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/alert.min.js") ? Url("alert.min.js") : Url("alert.js");
                              
                public static readonly string button_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/button.min.js") ? Url("button.min.js") : Url("button.js");
                              
                public static readonly string carousel_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/carousel.min.js") ? Url("carousel.min.js") : Url("carousel.js");
                              
                public static readonly string collapse_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/collapse.min.js") ? Url("collapse.min.js") : Url("collapse.js");
                              
                public static readonly string dropdown_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dropdown.min.js") ? Url("dropdown.min.js") : Url("dropdown.js");
                              
                public static readonly string modal_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modal.min.js") ? Url("modal.min.js") : Url("modal.js");
                              
                public static readonly string popover_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/popover.min.js") ? Url("popover.min.js") : Url("popover.js");
                              
                public static readonly string scrollspy_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/scrollspy.min.js") ? Url("scrollspy.min.js") : Url("scrollspy.js");
                              
                public static readonly string tab_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tab.min.js") ? Url("tab.min.js") : Url("tab.js");
                              
                public static readonly string tooltip_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.js") ? Url("tooltip.min.js") : Url("tooltip.js");
                              
                public static readonly string transition_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/transition.min.js") ? Url("transition.min.js") : Url("transition.js");
                              
                public static readonly string typeahead_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/typeahead.min.js") ? Url("typeahead.min.js") : Url("typeahead.js");
                              
            }
        
            public static readonly string jquery_1_7_2_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.7.2-vsdoc.min.js") ? Url("jquery-1.7.2-vsdoc.min.js") : Url("jquery-1.7.2-vsdoc.js");
                          
            public static readonly string jquery_1_7_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.7.2.min.js") ? Url("jquery-1.7.2.min.js") : Url("jquery-1.7.2.js");
                          
            public static readonly string jquery_1_7_2_min_js = Url("jquery-1.7.2.min.js");
            public static readonly string jquery_ui_1_8_20_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.8.20.min.js") ? Url("jquery-ui-1.8.20.min.js") : Url("jquery-ui-1.8.20.js");
                          
            public static readonly string jquery_ui_1_8_20_min_js = Url("jquery-ui-1.8.20.min.js");
            public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
                          
            public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
            public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
                          
            public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
                          
            public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
            public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
                          
            public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class kendoui {
                private const string URLPATH = "~/Scripts/libs/kendoui";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class cultures {
                    private const string URLPATH = "~/Scripts/libs/kendoui/cultures";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string kendo_culture_af_ZA_min_js = Url("kendo.culture.af-ZA.min.js");
                    public static readonly string kendo_culture_af_min_js = Url("kendo.culture.af.min.js");
                    public static readonly string kendo_culture_am_ET_min_js = Url("kendo.culture.am-ET.min.js");
                    public static readonly string kendo_culture_am_min_js = Url("kendo.culture.am.min.js");
                    public static readonly string kendo_culture_ar_AE_min_js = Url("kendo.culture.ar-AE.min.js");
                    public static readonly string kendo_culture_ar_BH_min_js = Url("kendo.culture.ar-BH.min.js");
                    public static readonly string kendo_culture_ar_DZ_min_js = Url("kendo.culture.ar-DZ.min.js");
                    public static readonly string kendo_culture_ar_EG_min_js = Url("kendo.culture.ar-EG.min.js");
                    public static readonly string kendo_culture_ar_IQ_min_js = Url("kendo.culture.ar-IQ.min.js");
                    public static readonly string kendo_culture_ar_JO_min_js = Url("kendo.culture.ar-JO.min.js");
                    public static readonly string kendo_culture_ar_KW_min_js = Url("kendo.culture.ar-KW.min.js");
                    public static readonly string kendo_culture_ar_LB_min_js = Url("kendo.culture.ar-LB.min.js");
                    public static readonly string kendo_culture_ar_LY_min_js = Url("kendo.culture.ar-LY.min.js");
                    public static readonly string kendo_culture_ar_MA_min_js = Url("kendo.culture.ar-MA.min.js");
                    public static readonly string kendo_culture_ar_OM_min_js = Url("kendo.culture.ar-OM.min.js");
                    public static readonly string kendo_culture_ar_QA_min_js = Url("kendo.culture.ar-QA.min.js");
                    public static readonly string kendo_culture_ar_SA_min_js = Url("kendo.culture.ar-SA.min.js");
                    public static readonly string kendo_culture_ar_SY_min_js = Url("kendo.culture.ar-SY.min.js");
                    public static readonly string kendo_culture_ar_TN_min_js = Url("kendo.culture.ar-TN.min.js");
                    public static readonly string kendo_culture_ar_YE_min_js = Url("kendo.culture.ar-YE.min.js");
                    public static readonly string kendo_culture_ar_min_js = Url("kendo.culture.ar.min.js");
                    public static readonly string kendo_culture_arn_CL_min_js = Url("kendo.culture.arn-CL.min.js");
                    public static readonly string kendo_culture_arn_min_js = Url("kendo.culture.arn.min.js");
                    public static readonly string kendo_culture_as_IN_min_js = Url("kendo.culture.as-IN.min.js");
                    public static readonly string kendo_culture_as_min_js = Url("kendo.culture.as.min.js");
                    public static readonly string kendo_culture_az_Cyrl_AZ_min_js = Url("kendo.culture.az-Cyrl-AZ.min.js");
                    public static readonly string kendo_culture_az_Cyrl_min_js = Url("kendo.culture.az-Cyrl.min.js");
                    public static readonly string kendo_culture_az_Latn_AZ_min_js = Url("kendo.culture.az-Latn-AZ.min.js");
                    public static readonly string kendo_culture_az_Latn_min_js = Url("kendo.culture.az-Latn.min.js");
                    public static readonly string kendo_culture_az_min_js = Url("kendo.culture.az.min.js");
                    public static readonly string kendo_culture_ba_RU_min_js = Url("kendo.culture.ba-RU.min.js");
                    public static readonly string kendo_culture_ba_min_js = Url("kendo.culture.ba.min.js");
                    public static readonly string kendo_culture_be_BY_min_js = Url("kendo.culture.be-BY.min.js");
                    public static readonly string kendo_culture_be_min_js = Url("kendo.culture.be.min.js");
                    public static readonly string kendo_culture_bg_BG_min_js = Url("kendo.culture.bg-BG.min.js");
                    public static readonly string kendo_culture_bg_min_js = Url("kendo.culture.bg.min.js");
                    public static readonly string kendo_culture_bn_BD_min_js = Url("kendo.culture.bn-BD.min.js");
                    public static readonly string kendo_culture_bn_IN_min_js = Url("kendo.culture.bn-IN.min.js");
                    public static readonly string kendo_culture_bn_min_js = Url("kendo.culture.bn.min.js");
                    public static readonly string kendo_culture_bo_CN_min_js = Url("kendo.culture.bo-CN.min.js");
                    public static readonly string kendo_culture_bo_min_js = Url("kendo.culture.bo.min.js");
                    public static readonly string kendo_culture_br_FR_min_js = Url("kendo.culture.br-FR.min.js");
                    public static readonly string kendo_culture_br_min_js = Url("kendo.culture.br.min.js");
                    public static readonly string kendo_culture_bs_Cyrl_BA_min_js = Url("kendo.culture.bs-Cyrl-BA.min.js");
                    public static readonly string kendo_culture_bs_Cyrl_min_js = Url("kendo.culture.bs-Cyrl.min.js");
                    public static readonly string kendo_culture_bs_Latn_BA_min_js = Url("kendo.culture.bs-Latn-BA.min.js");
                    public static readonly string kendo_culture_bs_Latn_min_js = Url("kendo.culture.bs-Latn.min.js");
                    public static readonly string kendo_culture_bs_min_js = Url("kendo.culture.bs.min.js");
                    public static readonly string kendo_culture_ca_ES_min_js = Url("kendo.culture.ca-ES.min.js");
                    public static readonly string kendo_culture_ca_min_js = Url("kendo.culture.ca.min.js");
                    public static readonly string kendo_culture_co_FR_min_js = Url("kendo.culture.co-FR.min.js");
                    public static readonly string kendo_culture_co_min_js = Url("kendo.culture.co.min.js");
                    public static readonly string kendo_culture_cs_CZ_min_js = Url("kendo.culture.cs-CZ.min.js");
                    public static readonly string kendo_culture_cs_min_js = Url("kendo.culture.cs.min.js");
                    public static readonly string kendo_culture_cy_GB_min_js = Url("kendo.culture.cy-GB.min.js");
                    public static readonly string kendo_culture_cy_min_js = Url("kendo.culture.cy.min.js");
                    public static readonly string kendo_culture_da_DK_min_js = Url("kendo.culture.da-DK.min.js");
                    public static readonly string kendo_culture_da_min_js = Url("kendo.culture.da.min.js");
                    public static readonly string kendo_culture_de_AT_min_js = Url("kendo.culture.de-AT.min.js");
                    public static readonly string kendo_culture_de_CH_min_js = Url("kendo.culture.de-CH.min.js");
                    public static readonly string kendo_culture_de_DE_min_js = Url("kendo.culture.de-DE.min.js");
                    public static readonly string kendo_culture_de_LI_min_js = Url("kendo.culture.de-LI.min.js");
                    public static readonly string kendo_culture_de_LU_min_js = Url("kendo.culture.de-LU.min.js");
                    public static readonly string kendo_culture_de_min_js = Url("kendo.culture.de.min.js");
                    public static readonly string kendo_culture_dsb_DE_min_js = Url("kendo.culture.dsb-DE.min.js");
                    public static readonly string kendo_culture_dsb_min_js = Url("kendo.culture.dsb.min.js");
                    public static readonly string kendo_culture_dv_MV_min_js = Url("kendo.culture.dv-MV.min.js");
                    public static readonly string kendo_culture_dv_min_js = Url("kendo.culture.dv.min.js");
                    public static readonly string kendo_culture_el_GR_min_js = Url("kendo.culture.el-GR.min.js");
                    public static readonly string kendo_culture_el_min_js = Url("kendo.culture.el.min.js");
                    public static readonly string kendo_culture_en_029_min_js = Url("kendo.culture.en-029.min.js");
                    public static readonly string kendo_culture_en_AU_min_js = Url("kendo.culture.en-AU.min.js");
                    public static readonly string kendo_culture_en_BZ_min_js = Url("kendo.culture.en-BZ.min.js");
                    public static readonly string kendo_culture_en_CA_min_js = Url("kendo.culture.en-CA.min.js");
                    public static readonly string kendo_culture_en_GB_min_js = Url("kendo.culture.en-GB.min.js");
                    public static readonly string kendo_culture_en_IE_min_js = Url("kendo.culture.en-IE.min.js");
                    public static readonly string kendo_culture_en_IN_min_js = Url("kendo.culture.en-IN.min.js");
                    public static readonly string kendo_culture_en_JM_min_js = Url("kendo.culture.en-JM.min.js");
                    public static readonly string kendo_culture_en_MY_min_js = Url("kendo.culture.en-MY.min.js");
                    public static readonly string kendo_culture_en_NZ_min_js = Url("kendo.culture.en-NZ.min.js");
                    public static readonly string kendo_culture_en_PH_min_js = Url("kendo.culture.en-PH.min.js");
                    public static readonly string kendo_culture_en_SG_min_js = Url("kendo.culture.en-SG.min.js");
                    public static readonly string kendo_culture_en_TT_min_js = Url("kendo.culture.en-TT.min.js");
                    public static readonly string kendo_culture_en_US_min_js = Url("kendo.culture.en-US.min.js");
                    public static readonly string kendo_culture_en_ZA_min_js = Url("kendo.culture.en-ZA.min.js");
                    public static readonly string kendo_culture_en_ZW_min_js = Url("kendo.culture.en-ZW.min.js");
                    public static readonly string kendo_culture_en_min_js = Url("kendo.culture.en.min.js");
                    public static readonly string kendo_culture_es_AR_min_js = Url("kendo.culture.es-AR.min.js");
                    public static readonly string kendo_culture_es_BO_min_js = Url("kendo.culture.es-BO.min.js");
                    public static readonly string kendo_culture_es_CL_min_js = Url("kendo.culture.es-CL.min.js");
                    public static readonly string kendo_culture_es_CO_min_js = Url("kendo.culture.es-CO.min.js");
                    public static readonly string kendo_culture_es_CR_min_js = Url("kendo.culture.es-CR.min.js");
                    public static readonly string kendo_culture_es_DO_min_js = Url("kendo.culture.es-DO.min.js");
                    public static readonly string kendo_culture_es_EC_min_js = Url("kendo.culture.es-EC.min.js");
                    public static readonly string kendo_culture_es_ES_min_js = Url("kendo.culture.es-ES.min.js");
                    public static readonly string kendo_culture_es_GT_min_js = Url("kendo.culture.es-GT.min.js");
                    public static readonly string kendo_culture_es_HN_min_js = Url("kendo.culture.es-HN.min.js");
                    public static readonly string kendo_culture_es_MX_min_js = Url("kendo.culture.es-MX.min.js");
                    public static readonly string kendo_culture_es_NI_min_js = Url("kendo.culture.es-NI.min.js");
                    public static readonly string kendo_culture_es_PA_min_js = Url("kendo.culture.es-PA.min.js");
                    public static readonly string kendo_culture_es_PE_min_js = Url("kendo.culture.es-PE.min.js");
                    public static readonly string kendo_culture_es_PR_min_js = Url("kendo.culture.es-PR.min.js");
                    public static readonly string kendo_culture_es_PY_min_js = Url("kendo.culture.es-PY.min.js");
                    public static readonly string kendo_culture_es_SV_min_js = Url("kendo.culture.es-SV.min.js");
                    public static readonly string kendo_culture_es_US_min_js = Url("kendo.culture.es-US.min.js");
                    public static readonly string kendo_culture_es_UY_min_js = Url("kendo.culture.es-UY.min.js");
                    public static readonly string kendo_culture_es_VE_min_js = Url("kendo.culture.es-VE.min.js");
                    public static readonly string kendo_culture_es_min_js = Url("kendo.culture.es.min.js");
                    public static readonly string kendo_culture_et_EE_min_js = Url("kendo.culture.et-EE.min.js");
                    public static readonly string kendo_culture_et_min_js = Url("kendo.culture.et.min.js");
                    public static readonly string kendo_culture_eu_ES_min_js = Url("kendo.culture.eu-ES.min.js");
                    public static readonly string kendo_culture_eu_min_js = Url("kendo.culture.eu.min.js");
                    public static readonly string kendo_culture_fa_IR_min_js = Url("kendo.culture.fa-IR.min.js");
                    public static readonly string kendo_culture_fa_min_js = Url("kendo.culture.fa.min.js");
                    public static readonly string kendo_culture_fi_FI_min_js = Url("kendo.culture.fi-FI.min.js");
                    public static readonly string kendo_culture_fi_min_js = Url("kendo.culture.fi.min.js");
                    public static readonly string kendo_culture_fil_PH_min_js = Url("kendo.culture.fil-PH.min.js");
                    public static readonly string kendo_culture_fil_min_js = Url("kendo.culture.fil.min.js");
                    public static readonly string kendo_culture_fo_FO_min_js = Url("kendo.culture.fo-FO.min.js");
                    public static readonly string kendo_culture_fo_min_js = Url("kendo.culture.fo.min.js");
                    public static readonly string kendo_culture_fr_BE_min_js = Url("kendo.culture.fr-BE.min.js");
                    public static readonly string kendo_culture_fr_CA_min_js = Url("kendo.culture.fr-CA.min.js");
                    public static readonly string kendo_culture_fr_CH_min_js = Url("kendo.culture.fr-CH.min.js");
                    public static readonly string kendo_culture_fr_FR_min_js = Url("kendo.culture.fr-FR.min.js");
                    public static readonly string kendo_culture_fr_LU_min_js = Url("kendo.culture.fr-LU.min.js");
                    public static readonly string kendo_culture_fr_MC_min_js = Url("kendo.culture.fr-MC.min.js");
                    public static readonly string kendo_culture_fr_min_js = Url("kendo.culture.fr.min.js");
                    public static readonly string kendo_culture_fy_NL_min_js = Url("kendo.culture.fy-NL.min.js");
                    public static readonly string kendo_culture_fy_min_js = Url("kendo.culture.fy.min.js");
                    public static readonly string kendo_culture_ga_IE_min_js = Url("kendo.culture.ga-IE.min.js");
                    public static readonly string kendo_culture_ga_min_js = Url("kendo.culture.ga.min.js");
                    public static readonly string kendo_culture_gd_GB_min_js = Url("kendo.culture.gd-GB.min.js");
                    public static readonly string kendo_culture_gd_min_js = Url("kendo.culture.gd.min.js");
                    public static readonly string kendo_culture_gl_ES_min_js = Url("kendo.culture.gl-ES.min.js");
                    public static readonly string kendo_culture_gl_min_js = Url("kendo.culture.gl.min.js");
                    public static readonly string kendo_culture_gsw_FR_min_js = Url("kendo.culture.gsw-FR.min.js");
                    public static readonly string kendo_culture_gsw_min_js = Url("kendo.culture.gsw.min.js");
                    public static readonly string kendo_culture_gu_IN_min_js = Url("kendo.culture.gu-IN.min.js");
                    public static readonly string kendo_culture_gu_min_js = Url("kendo.culture.gu.min.js");
                    public static readonly string kendo_culture_ha_Latn_NG_min_js = Url("kendo.culture.ha-Latn-NG.min.js");
                    public static readonly string kendo_culture_ha_Latn_min_js = Url("kendo.culture.ha-Latn.min.js");
                    public static readonly string kendo_culture_ha_min_js = Url("kendo.culture.ha.min.js");
                    public static readonly string kendo_culture_he_IL_min_js = Url("kendo.culture.he-IL.min.js");
                    public static readonly string kendo_culture_he_min_js = Url("kendo.culture.he.min.js");
                    public static readonly string kendo_culture_hi_IN_min_js = Url("kendo.culture.hi-IN.min.js");
                    public static readonly string kendo_culture_hi_min_js = Url("kendo.culture.hi.min.js");
                    public static readonly string kendo_culture_hr_BA_min_js = Url("kendo.culture.hr-BA.min.js");
                    public static readonly string kendo_culture_hr_HR_min_js = Url("kendo.culture.hr-HR.min.js");
                    public static readonly string kendo_culture_hr_min_js = Url("kendo.culture.hr.min.js");
                    public static readonly string kendo_culture_hsb_DE_min_js = Url("kendo.culture.hsb-DE.min.js");
                    public static readonly string kendo_culture_hsb_min_js = Url("kendo.culture.hsb.min.js");
                    public static readonly string kendo_culture_hu_HU_min_js = Url("kendo.culture.hu-HU.min.js");
                    public static readonly string kendo_culture_hu_min_js = Url("kendo.culture.hu.min.js");
                    public static readonly string kendo_culture_hy_AM_min_js = Url("kendo.culture.hy-AM.min.js");
                    public static readonly string kendo_culture_hy_min_js = Url("kendo.culture.hy.min.js");
                    public static readonly string kendo_culture_id_ID_min_js = Url("kendo.culture.id-ID.min.js");
                    public static readonly string kendo_culture_id_min_js = Url("kendo.culture.id.min.js");
                    public static readonly string kendo_culture_ig_NG_min_js = Url("kendo.culture.ig-NG.min.js");
                    public static readonly string kendo_culture_ig_min_js = Url("kendo.culture.ig.min.js");
                    public static readonly string kendo_culture_ii_CN_min_js = Url("kendo.culture.ii-CN.min.js");
                    public static readonly string kendo_culture_ii_min_js = Url("kendo.culture.ii.min.js");
                    public static readonly string kendo_culture_is_IS_min_js = Url("kendo.culture.is-IS.min.js");
                    public static readonly string kendo_culture_is_min_js = Url("kendo.culture.is.min.js");
                    public static readonly string kendo_culture_it_CH_min_js = Url("kendo.culture.it-CH.min.js");
                    public static readonly string kendo_culture_it_IT_min_js = Url("kendo.culture.it-IT.min.js");
                    public static readonly string kendo_culture_it_min_js = Url("kendo.culture.it.min.js");
                    public static readonly string kendo_culture_iu_Cans_CA_min_js = Url("kendo.culture.iu-Cans-CA.min.js");
                    public static readonly string kendo_culture_iu_Cans_min_js = Url("kendo.culture.iu-Cans.min.js");
                    public static readonly string kendo_culture_iu_Latn_CA_min_js = Url("kendo.culture.iu-Latn-CA.min.js");
                    public static readonly string kendo_culture_iu_Latn_min_js = Url("kendo.culture.iu-Latn.min.js");
                    public static readonly string kendo_culture_iu_min_js = Url("kendo.culture.iu.min.js");
                    public static readonly string kendo_culture_ja_JP_min_js = Url("kendo.culture.ja-JP.min.js");
                    public static readonly string kendo_culture_ja_min_js = Url("kendo.culture.ja.min.js");
                    public static readonly string kendo_culture_ka_GE_min_js = Url("kendo.culture.ka-GE.min.js");
                    public static readonly string kendo_culture_ka_min_js = Url("kendo.culture.ka.min.js");
                    public static readonly string kendo_culture_kk_KZ_min_js = Url("kendo.culture.kk-KZ.min.js");
                    public static readonly string kendo_culture_kk_min_js = Url("kendo.culture.kk.min.js");
                    public static readonly string kendo_culture_kl_GL_min_js = Url("kendo.culture.kl-GL.min.js");
                    public static readonly string kendo_culture_kl_min_js = Url("kendo.culture.kl.min.js");
                    public static readonly string kendo_culture_km_KH_min_js = Url("kendo.culture.km-KH.min.js");
                    public static readonly string kendo_culture_km_min_js = Url("kendo.culture.km.min.js");
                    public static readonly string kendo_culture_kn_IN_min_js = Url("kendo.culture.kn-IN.min.js");
                    public static readonly string kendo_culture_kn_min_js = Url("kendo.culture.kn.min.js");
                    public static readonly string kendo_culture_ko_KR_min_js = Url("kendo.culture.ko-KR.min.js");
                    public static readonly string kendo_culture_ko_min_js = Url("kendo.culture.ko.min.js");
                    public static readonly string kendo_culture_kok_IN_min_js = Url("kendo.culture.kok-IN.min.js");
                    public static readonly string kendo_culture_kok_min_js = Url("kendo.culture.kok.min.js");
                    public static readonly string kendo_culture_ky_KG_min_js = Url("kendo.culture.ky-KG.min.js");
                    public static readonly string kendo_culture_ky_min_js = Url("kendo.culture.ky.min.js");
                    public static readonly string kendo_culture_lb_LU_min_js = Url("kendo.culture.lb-LU.min.js");
                    public static readonly string kendo_culture_lb_min_js = Url("kendo.culture.lb.min.js");
                    public static readonly string kendo_culture_lo_LA_min_js = Url("kendo.culture.lo-LA.min.js");
                    public static readonly string kendo_culture_lo_min_js = Url("kendo.culture.lo.min.js");
                    public static readonly string kendo_culture_lt_LT_min_js = Url("kendo.culture.lt-LT.min.js");
                    public static readonly string kendo_culture_lt_min_js = Url("kendo.culture.lt.min.js");
                    public static readonly string kendo_culture_lv_LV_min_js = Url("kendo.culture.lv-LV.min.js");
                    public static readonly string kendo_culture_lv_min_js = Url("kendo.culture.lv.min.js");
                    public static readonly string kendo_culture_mi_NZ_min_js = Url("kendo.culture.mi-NZ.min.js");
                    public static readonly string kendo_culture_mi_min_js = Url("kendo.culture.mi.min.js");
                    public static readonly string kendo_culture_mk_MK_min_js = Url("kendo.culture.mk-MK.min.js");
                    public static readonly string kendo_culture_mk_min_js = Url("kendo.culture.mk.min.js");
                    public static readonly string kendo_culture_ml_IN_min_js = Url("kendo.culture.ml-IN.min.js");
                    public static readonly string kendo_culture_ml_min_js = Url("kendo.culture.ml.min.js");
                    public static readonly string kendo_culture_mn_Cyrl_min_js = Url("kendo.culture.mn-Cyrl.min.js");
                    public static readonly string kendo_culture_mn_MN_min_js = Url("kendo.culture.mn-MN.min.js");
                    public static readonly string kendo_culture_mn_Mong_CN_min_js = Url("kendo.culture.mn-Mong-CN.min.js");
                    public static readonly string kendo_culture_mn_Mong_min_js = Url("kendo.culture.mn-Mong.min.js");
                    public static readonly string kendo_culture_mn_min_js = Url("kendo.culture.mn.min.js");
                    public static readonly string kendo_culture_moh_CA_min_js = Url("kendo.culture.moh-CA.min.js");
                    public static readonly string kendo_culture_moh_min_js = Url("kendo.culture.moh.min.js");
                    public static readonly string kendo_culture_mr_IN_min_js = Url("kendo.culture.mr-IN.min.js");
                    public static readonly string kendo_culture_mr_min_js = Url("kendo.culture.mr.min.js");
                    public static readonly string kendo_culture_ms_BN_min_js = Url("kendo.culture.ms-BN.min.js");
                    public static readonly string kendo_culture_ms_MY_min_js = Url("kendo.culture.ms-MY.min.js");
                    public static readonly string kendo_culture_ms_min_js = Url("kendo.culture.ms.min.js");
                    public static readonly string kendo_culture_mt_MT_min_js = Url("kendo.culture.mt-MT.min.js");
                    public static readonly string kendo_culture_mt_min_js = Url("kendo.culture.mt.min.js");
                    public static readonly string kendo_culture_nb_NO_min_js = Url("kendo.culture.nb-NO.min.js");
                    public static readonly string kendo_culture_nb_min_js = Url("kendo.culture.nb.min.js");
                    public static readonly string kendo_culture_ne_NP_min_js = Url("kendo.culture.ne-NP.min.js");
                    public static readonly string kendo_culture_ne_min_js = Url("kendo.culture.ne.min.js");
                    public static readonly string kendo_culture_nl_BE_min_js = Url("kendo.culture.nl-BE.min.js");
                    public static readonly string kendo_culture_nl_NL_min_js = Url("kendo.culture.nl-NL.min.js");
                    public static readonly string kendo_culture_nl_min_js = Url("kendo.culture.nl.min.js");
                    public static readonly string kendo_culture_nn_NO_min_js = Url("kendo.culture.nn-NO.min.js");
                    public static readonly string kendo_culture_nn_min_js = Url("kendo.culture.nn.min.js");
                    public static readonly string kendo_culture_no_min_js = Url("kendo.culture.no.min.js");
                    public static readonly string kendo_culture_nso_ZA_min_js = Url("kendo.culture.nso-ZA.min.js");
                    public static readonly string kendo_culture_nso_min_js = Url("kendo.culture.nso.min.js");
                    public static readonly string kendo_culture_oc_FR_min_js = Url("kendo.culture.oc-FR.min.js");
                    public static readonly string kendo_culture_oc_min_js = Url("kendo.culture.oc.min.js");
                    public static readonly string kendo_culture_or_IN_min_js = Url("kendo.culture.or-IN.min.js");
                    public static readonly string kendo_culture_or_min_js = Url("kendo.culture.or.min.js");
                    public static readonly string kendo_culture_pa_IN_min_js = Url("kendo.culture.pa-IN.min.js");
                    public static readonly string kendo_culture_pa_min_js = Url("kendo.culture.pa.min.js");
                    public static readonly string kendo_culture_pl_PL_min_js = Url("kendo.culture.pl-PL.min.js");
                    public static readonly string kendo_culture_pl_min_js = Url("kendo.culture.pl.min.js");
                    public static readonly string kendo_culture_prs_AF_min_js = Url("kendo.culture.prs-AF.min.js");
                    public static readonly string kendo_culture_prs_min_js = Url("kendo.culture.prs.min.js");
                    public static readonly string kendo_culture_ps_AF_min_js = Url("kendo.culture.ps-AF.min.js");
                    public static readonly string kendo_culture_ps_min_js = Url("kendo.culture.ps.min.js");
                    public static readonly string kendo_culture_pt_BR_min_js = Url("kendo.culture.pt-BR.min.js");
                    public static readonly string kendo_culture_pt_PT_min_js = Url("kendo.culture.pt-PT.min.js");
                    public static readonly string kendo_culture_pt_min_js = Url("kendo.culture.pt.min.js");
                    public static readonly string kendo_culture_qut_GT_min_js = Url("kendo.culture.qut-GT.min.js");
                    public static readonly string kendo_culture_qut_min_js = Url("kendo.culture.qut.min.js");
                    public static readonly string kendo_culture_quz_BO_min_js = Url("kendo.culture.quz-BO.min.js");
                    public static readonly string kendo_culture_quz_EC_min_js = Url("kendo.culture.quz-EC.min.js");
                    public static readonly string kendo_culture_quz_PE_min_js = Url("kendo.culture.quz-PE.min.js");
                    public static readonly string kendo_culture_quz_min_js = Url("kendo.culture.quz.min.js");
                    public static readonly string kendo_culture_rm_CH_min_js = Url("kendo.culture.rm-CH.min.js");
                    public static readonly string kendo_culture_rm_min_js = Url("kendo.culture.rm.min.js");
                    public static readonly string kendo_culture_ro_RO_min_js = Url("kendo.culture.ro-RO.min.js");
                    public static readonly string kendo_culture_ro_min_js = Url("kendo.culture.ro.min.js");
                    public static readonly string kendo_culture_ru_RU_min_js = Url("kendo.culture.ru-RU.min.js");
                    public static readonly string kendo_culture_ru_min_js = Url("kendo.culture.ru.min.js");
                    public static readonly string kendo_culture_rw_RW_min_js = Url("kendo.culture.rw-RW.min.js");
                    public static readonly string kendo_culture_rw_min_js = Url("kendo.culture.rw.min.js");
                    public static readonly string kendo_culture_sa_IN_min_js = Url("kendo.culture.sa-IN.min.js");
                    public static readonly string kendo_culture_sa_min_js = Url("kendo.culture.sa.min.js");
                    public static readonly string kendo_culture_sah_RU_min_js = Url("kendo.culture.sah-RU.min.js");
                    public static readonly string kendo_culture_sah_min_js = Url("kendo.culture.sah.min.js");
                    public static readonly string kendo_culture_se_FI_min_js = Url("kendo.culture.se-FI.min.js");
                    public static readonly string kendo_culture_se_NO_min_js = Url("kendo.culture.se-NO.min.js");
                    public static readonly string kendo_culture_se_SE_min_js = Url("kendo.culture.se-SE.min.js");
                    public static readonly string kendo_culture_se_min_js = Url("kendo.culture.se.min.js");
                    public static readonly string kendo_culture_si_LK_min_js = Url("kendo.culture.si-LK.min.js");
                    public static readonly string kendo_culture_si_min_js = Url("kendo.culture.si.min.js");
                    public static readonly string kendo_culture_sk_SK_min_js = Url("kendo.culture.sk-SK.min.js");
                    public static readonly string kendo_culture_sk_min_js = Url("kendo.culture.sk.min.js");
                    public static readonly string kendo_culture_sl_SI_min_js = Url("kendo.culture.sl-SI.min.js");
                    public static readonly string kendo_culture_sl_min_js = Url("kendo.culture.sl.min.js");
                    public static readonly string kendo_culture_sma_NO_min_js = Url("kendo.culture.sma-NO.min.js");
                    public static readonly string kendo_culture_sma_SE_min_js = Url("kendo.culture.sma-SE.min.js");
                    public static readonly string kendo_culture_sma_min_js = Url("kendo.culture.sma.min.js");
                    public static readonly string kendo_culture_smj_NO_min_js = Url("kendo.culture.smj-NO.min.js");
                    public static readonly string kendo_culture_smj_SE_min_js = Url("kendo.culture.smj-SE.min.js");
                    public static readonly string kendo_culture_smj_min_js = Url("kendo.culture.smj.min.js");
                    public static readonly string kendo_culture_smn_FI_min_js = Url("kendo.culture.smn-FI.min.js");
                    public static readonly string kendo_culture_smn_min_js = Url("kendo.culture.smn.min.js");
                    public static readonly string kendo_culture_sms_FI_min_js = Url("kendo.culture.sms-FI.min.js");
                    public static readonly string kendo_culture_sms_min_js = Url("kendo.culture.sms.min.js");
                    public static readonly string kendo_culture_sq_AL_min_js = Url("kendo.culture.sq-AL.min.js");
                    public static readonly string kendo_culture_sq_min_js = Url("kendo.culture.sq.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_BA_min_js = Url("kendo.culture.sr-Cyrl-BA.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_CS_min_js = Url("kendo.culture.sr-Cyrl-CS.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_ME_min_js = Url("kendo.culture.sr-Cyrl-ME.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_RS_min_js = Url("kendo.culture.sr-Cyrl-RS.min.js");
                    public static readonly string kendo_culture_sr_Cyrl_min_js = Url("kendo.culture.sr-Cyrl.min.js");
                    public static readonly string kendo_culture_sr_Latn_BA_min_js = Url("kendo.culture.sr-Latn-BA.min.js");
                    public static readonly string kendo_culture_sr_Latn_CS_min_js = Url("kendo.culture.sr-Latn-CS.min.js");
                    public static readonly string kendo_culture_sr_Latn_ME_min_js = Url("kendo.culture.sr-Latn-ME.min.js");
                    public static readonly string kendo_culture_sr_Latn_RS_min_js = Url("kendo.culture.sr-Latn-RS.min.js");
                    public static readonly string kendo_culture_sr_Latn_min_js = Url("kendo.culture.sr-Latn.min.js");
                    public static readonly string kendo_culture_sr_min_js = Url("kendo.culture.sr.min.js");
                    public static readonly string kendo_culture_sv_FI_min_js = Url("kendo.culture.sv-FI.min.js");
                    public static readonly string kendo_culture_sv_SE_min_js = Url("kendo.culture.sv-SE.min.js");
                    public static readonly string kendo_culture_sv_min_js = Url("kendo.culture.sv.min.js");
                    public static readonly string kendo_culture_sw_KE_min_js = Url("kendo.culture.sw-KE.min.js");
                    public static readonly string kendo_culture_sw_min_js = Url("kendo.culture.sw.min.js");
                    public static readonly string kendo_culture_syr_SY_min_js = Url("kendo.culture.syr-SY.min.js");
                    public static readonly string kendo_culture_syr_min_js = Url("kendo.culture.syr.min.js");
                    public static readonly string kendo_culture_ta_IN_min_js = Url("kendo.culture.ta-IN.min.js");
                    public static readonly string kendo_culture_ta_min_js = Url("kendo.culture.ta.min.js");
                    public static readonly string kendo_culture_te_IN_min_js = Url("kendo.culture.te-IN.min.js");
                    public static readonly string kendo_culture_te_min_js = Url("kendo.culture.te.min.js");
                    public static readonly string kendo_culture_tg_Cyrl_TJ_min_js = Url("kendo.culture.tg-Cyrl-TJ.min.js");
                    public static readonly string kendo_culture_tg_Cyrl_min_js = Url("kendo.culture.tg-Cyrl.min.js");
                    public static readonly string kendo_culture_tg_min_js = Url("kendo.culture.tg.min.js");
                    public static readonly string kendo_culture_th_TH_min_js = Url("kendo.culture.th-TH.min.js");
                    public static readonly string kendo_culture_th_min_js = Url("kendo.culture.th.min.js");
                    public static readonly string kendo_culture_tk_TM_min_js = Url("kendo.culture.tk-TM.min.js");
                    public static readonly string kendo_culture_tk_min_js = Url("kendo.culture.tk.min.js");
                    public static readonly string kendo_culture_tn_ZA_min_js = Url("kendo.culture.tn-ZA.min.js");
                    public static readonly string kendo_culture_tn_min_js = Url("kendo.culture.tn.min.js");
                    public static readonly string kendo_culture_tr_TR_min_js = Url("kendo.culture.tr-TR.min.js");
                    public static readonly string kendo_culture_tr_min_js = Url("kendo.culture.tr.min.js");
                    public static readonly string kendo_culture_tt_RU_min_js = Url("kendo.culture.tt-RU.min.js");
                    public static readonly string kendo_culture_tt_min_js = Url("kendo.culture.tt.min.js");
                    public static readonly string kendo_culture_tzm_Latn_DZ_min_js = Url("kendo.culture.tzm-Latn-DZ.min.js");
                    public static readonly string kendo_culture_tzm_Latn_min_js = Url("kendo.culture.tzm-Latn.min.js");
                    public static readonly string kendo_culture_tzm_min_js = Url("kendo.culture.tzm.min.js");
                    public static readonly string kendo_culture_ug_CN_min_js = Url("kendo.culture.ug-CN.min.js");
                    public static readonly string kendo_culture_ug_min_js = Url("kendo.culture.ug.min.js");
                    public static readonly string kendo_culture_uk_UA_min_js = Url("kendo.culture.uk-UA.min.js");
                    public static readonly string kendo_culture_uk_min_js = Url("kendo.culture.uk.min.js");
                    public static readonly string kendo_culture_ur_PK_min_js = Url("kendo.culture.ur-PK.min.js");
                    public static readonly string kendo_culture_ur_min_js = Url("kendo.culture.ur.min.js");
                    public static readonly string kendo_culture_uz_Cyrl_UZ_min_js = Url("kendo.culture.uz-Cyrl-UZ.min.js");
                    public static readonly string kendo_culture_uz_Cyrl_min_js = Url("kendo.culture.uz-Cyrl.min.js");
                    public static readonly string kendo_culture_uz_Latn_UZ_min_js = Url("kendo.culture.uz-Latn-UZ.min.js");
                    public static readonly string kendo_culture_uz_Latn_min_js = Url("kendo.culture.uz-Latn.min.js");
                    public static readonly string kendo_culture_uz_min_js = Url("kendo.culture.uz.min.js");
                    public static readonly string kendo_culture_vi_VN_min_js = Url("kendo.culture.vi-VN.min.js");
                    public static readonly string kendo_culture_vi_min_js = Url("kendo.culture.vi.min.js");
                    public static readonly string kendo_culture_wo_SN_min_js = Url("kendo.culture.wo-SN.min.js");
                    public static readonly string kendo_culture_wo_min_js = Url("kendo.culture.wo.min.js");
                    public static readonly string kendo_culture_xh_ZA_min_js = Url("kendo.culture.xh-ZA.min.js");
                    public static readonly string kendo_culture_xh_min_js = Url("kendo.culture.xh.min.js");
                    public static readonly string kendo_culture_yo_NG_min_js = Url("kendo.culture.yo-NG.min.js");
                    public static readonly string kendo_culture_yo_min_js = Url("kendo.culture.yo.min.js");
                    public static readonly string kendo_culture_zh_CHS_min_js = Url("kendo.culture.zh-CHS.min.js");
                    public static readonly string kendo_culture_zh_CHT_min_js = Url("kendo.culture.zh-CHT.min.js");
                    public static readonly string kendo_culture_zh_CN_min_js = Url("kendo.culture.zh-CN.min.js");
                    public static readonly string kendo_culture_zh_Hans_min_js = Url("kendo.culture.zh-Hans.min.js");
                    public static readonly string kendo_culture_zh_Hant_min_js = Url("kendo.culture.zh-Hant.min.js");
                    public static readonly string kendo_culture_zh_HK_min_js = Url("kendo.culture.zh-HK.min.js");
                    public static readonly string kendo_culture_zh_MO_min_js = Url("kendo.culture.zh-MO.min.js");
                    public static readonly string kendo_culture_zh_SG_min_js = Url("kendo.culture.zh-SG.min.js");
                    public static readonly string kendo_culture_zh_TW_min_js = Url("kendo.culture.zh-TW.min.js");
                    public static readonly string kendo_culture_zh_min_js = Url("kendo.culture.zh.min.js");
                    public static readonly string kendo_culture_zu_ZA_min_js = Url("kendo.culture.zu-ZA.min.js");
                    public static readonly string kendo_culture_zu_min_js = Url("kendo.culture.zu.min.js");
                }
            
                public static readonly string jquery_min_js = Url("jquery.min.js");
                public static readonly string kendo_all_min_js = Url("kendo.all.min.js");
                public static readonly string kendo_autocomplete_min_js = Url("kendo.autocomplete.min.js");
                public static readonly string kendo_binder_min_js = Url("kendo.binder.min.js");
                public static readonly string kendo_calendar_min_js = Url("kendo.calendar.min.js");
                public static readonly string kendo_combobox_min_js = Url("kendo.combobox.min.js");
                public static readonly string kendo_core_min_js = Url("kendo.core.min.js");
                public static readonly string kendo_data_min_js = Url("kendo.data.min.js");
                public static readonly string kendo_data_odata_min_js = Url("kendo.data.odata.min.js");
                public static readonly string kendo_data_xml_min_js = Url("kendo.data.xml.min.js");
                public static readonly string kendo_dataviz_chart_min_js = Url("kendo.dataviz.chart.min.js");
                public static readonly string kendo_dataviz_core_min_js = Url("kendo.dataviz.core.min.js");
                public static readonly string kendo_dataviz_gauge_min_js = Url("kendo.dataviz.gauge.min.js");
                public static readonly string kendo_dataviz_min_js = Url("kendo.dataviz.min.js");
                public static readonly string kendo_dataviz_svg_min_js = Url("kendo.dataviz.svg.min.js");
                public static readonly string kendo_dataviz_themes_min_js = Url("kendo.dataviz.themes.min.js");
                public static readonly string kendo_dataviz_vml_min_js = Url("kendo.dataviz.vml.min.js");
                public static readonly string kendo_datepicker_min_js = Url("kendo.datepicker.min.js");
                public static readonly string kendo_draganddrop_min_js = Url("kendo.draganddrop.min.js");
                public static readonly string kendo_dropdownlist_min_js = Url("kendo.dropdownlist.min.js");
                public static readonly string kendo_editable_min_js = Url("kendo.editable.min.js");
                public static readonly string kendo_editor_min_js = Url("kendo.editor.min.js");
                public static readonly string kendo_filtermenu_min_js = Url("kendo.filtermenu.min.js");
                public static readonly string kendo_fx_min_js = Url("kendo.fx.min.js");
                public static readonly string kendo_grid_min_js = Url("kendo.grid.min.js");
                public static readonly string kendo_groupable_min_js = Url("kendo.groupable.min.js");
                public static readonly string kendo_history_min_js = Url("kendo.history.min.js");
                public static readonly string kendo_list_min_js = Url("kendo.list.min.js");
                public static readonly string kendo_listview_min_js = Url("kendo.listview.min.js");
                public static readonly string kendo_menu_min_js = Url("kendo.menu.min.js");
                public static readonly string kendo_mobile_actionsheet_min_js = Url("kendo.mobile.actionsheet.min.js");
                public static readonly string kendo_mobile_application_min_js = Url("kendo.mobile.application.min.js");
                public static readonly string kendo_mobile_button_min_js = Url("kendo.mobile.button.min.js");
                public static readonly string kendo_mobile_buttongroup_min_js = Url("kendo.mobile.buttongroup.min.js");
                public static readonly string kendo_mobile_listview_min_js = Url("kendo.mobile.listview.min.js");
                public static readonly string kendo_mobile_min_js = Url("kendo.mobile.min.js");
                public static readonly string kendo_mobile_navbar_min_js = Url("kendo.mobile.navbar.min.js");
                public static readonly string kendo_mobile_scroller_min_js = Url("kendo.mobile.scroller.min.js");
                public static readonly string kendo_mobile_scrollview_min_js = Url("kendo.mobile.scrollview.min.js");
                public static readonly string kendo_mobile_shim_min_js = Url("kendo.mobile.shim.min.js");
                public static readonly string kendo_mobile_switch_min_js = Url("kendo.mobile.switch.min.js");
                public static readonly string kendo_mobile_tabstrip_min_js = Url("kendo.mobile.tabstrip.min.js");
                public static readonly string kendo_mobile_view_min_js = Url("kendo.mobile.view.min.js");
                public static readonly string kendo_numerictextbox_min_js = Url("kendo.numerictextbox.min.js");
                public static readonly string kendo_pager_min_js = Url("kendo.pager.min.js");
                public static readonly string kendo_panelbar_min_js = Url("kendo.panelbar.min.js");
                public static readonly string kendo_popup_min_js = Url("kendo.popup.min.js");
                public static readonly string kendo_reorderable_min_js = Url("kendo.reorderable.min.js");
                public static readonly string kendo_resizable_min_js = Url("kendo.resizable.min.js");
                public static readonly string kendo_selectable_min_js = Url("kendo.selectable.min.js");
                public static readonly string kendo_slider_min_js = Url("kendo.slider.min.js");
                public static readonly string kendo_sortable_min_js = Url("kendo.sortable.min.js");
                public static readonly string kendo_splitter_min_js = Url("kendo.splitter.min.js");
                public static readonly string kendo_tabstrip_min_js = Url("kendo.tabstrip.min.js");
                public static readonly string kendo_timepicker_min_js = Url("kendo.timepicker.min.js");
                public static readonly string kendo_treeview_min_js = Url("kendo.treeview.min.js");
                public static readonly string kendo_upload_min_js = Url("kendo.upload.min.js");
                public static readonly string kendo_validator_min_js = Url("kendo.validator.min.js");
                public static readonly string kendo_web_min_js = Url("kendo.web.min.js");
                public static readonly string kendo_window_min_js = Url("kendo.window.min.js");
            }
        
            public static readonly string knockout_2_1_0_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.1.0.debug.min.js") ? Url("knockout-2.1.0.debug.min.js") : Url("knockout-2.1.0.debug.js");
                          
            public static readonly string knockout_2_1_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.1.0.min.js") ? Url("knockout-2.1.0.min.js") : Url("knockout-2.1.0.js");
                          
            public static readonly string modernizr_2_0_6_development_only_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.0.6-development-only.min.js") ? Url("modernizr-2.0.6-development-only.min.js") : Url("modernizr-2.0.6-development-only.js");
                          
        }
    
        public static readonly string modernizr_2_5_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.5.3.min.js") ? Url("modernizr-2.5.3.min.js") : Url("modernizr-2.5.3.js");
                      
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                     
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    private const string URLPATH = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                }
            
            }
        
        }
    
    }

}

public static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;


    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591




